name: status_dashboard_dev

services:
  app:
    image: status_dashboard_dev
    build:
      context: ../../../
      dockerfile: ./docker/exclude/dev/Dockerfile
      tags:
        - "status_dashboard_dev:latest"
    env_file:
      - ./.env.dev
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    container_name: status_dashboard_dev

  db:
    image: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask_dev
    container_name: db

volumes:
  postgres_data_dev:
    name: postgres_data_dev
