name: status_dashboard_prod

services:
  app:
    image: status_dashboard_prod
    build:
      context: ../../../
      dockerfile: ./docker/exclude/prod/Dockerfile
      tags:
        - "status_dashboard_prod:latest"
    env_file:
      - ./.env.prod
    ports:
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    container_name: status_dashboard_prod

  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod.db
    container_name: db_prod

volumes:
  postgres_data_prod:
    name: postgres_data_prod
