name: Flask

on: [push]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r services/web/requirements.txt black isort pylint

    - name: Run black
      run: |
        black $(git ls-files *.py)

    - name: Run isort
      run: |
        isort --profile=black $(git ls-files *.py)

    - name: Run pylint
      run: |
        pylint --disable=R0903 --fail-under=8.0 $(git ls-files *.py)

    - name: Commit & Push Changes
      if: ${{ success() }}
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "chore: auto format and lint passed"
        branch: ${{ github.ref_name }}
